Lusiadas-Solucao-Web/Lusiadas-Solucao-Web/Models/ATP/ATPDashModel.cs
using LDFHelper.Helpers;
using LusiadasDAL;
using Oracle.ManagedDataAccess.Client;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;

namespace LusiadasSolucaoWeb.Models
{
    public class ATPDashModel : LDFTableModel
    {



        #region ATPDashModel

        

        private string schema = "MEDICO";
        private string tabela = "V_DASH_DESLOC_ATP_V3";
        private string query = "*";
        private string condition = "";
        private string orderQ = "DT_CONS";

        public ATPDashModel()
        {

            pageSize = (int)HttpContext.Current.Session["Tabela"];  
            
            dbParams = new LDFTableDBParams(GetConnectionString(), schema, tabela, query, condition, orderQ, null, null);
            objType = typeof(VwDashboardATP);

            LDFTableHeaders();
            ReArrangeHeaders();
        }



        public ATPDashModel(int num)
        {

            pageSize = num;

            dbParams = new LDFTableDBParams(GetConnectionString(), schema, tabela, query, condition, orderQ, null, null);
            objType = typeof(VwDashboardATP);

            LDFTableHeaders();
            ReArrangeHeaders();
        }

        private string GetConnectionString()
        {
            string nome = "";
            try
            {
                if (String.IsNullOrEmpty(HttpContext.Current.Session[Constants.SS_LOCAL_CONN].ToString()))
                {
                    nome = "BDHPT";

                }
                else
                {
                    nome = HttpContext.Current.Session[Constants.SS_LOCAL_CONN].ToString();

                }

                return nome;

            }
            catch (Exception e)
            {
                nome = "BDHPT";
                return nome;
            }
        }

        private void ReArrangeHeaders()
        {
            foreach (LDFTableHeader item in list_headers)
            {

                if (item.headerID == "DT_CONS" || item.headerID == "IMAGEM" || item.headerID == "COR_TRIAGEM" || item.headerID == "DT_NOTA_MEDICA" || item.headerID == "LOCALIZACAO" || item.headerID == "MEDICO_NOME" || item.headerID == "DOENTE" || item.headerID == "ANALISES_OK" || item.headerID == "MEDICACAO_PRESCRITA_PCE" || item.headerID == "IMAGIOLOGIA_REQUESITADOS" || item.headerID == "ECG_REQUESITADOS" || item.headerID == "CEXTERNA_REQUISITADOS")
                item.headerStyle.Add("text-align", "center");
            }
        }


        public void LDFTableTreatData()
        {
            try
            {

                string nomeDescr = "", curdate = "", dtnasc = "";
                string medicacao_presc;
                int medAMB, medPCE, medAGL, mEDPGL;


                foreach (LDFTableRow item in list_rows)
                {

                    #region NumeroDoente
                    item.rowItems.First(q => q.itemColumnName == "DOENTE").itemValue = Generic.GetItemValue(item, "DOENTE");
                    #endregion

                    #region Nome Doente
                    dtnasc = Generic.GetItemValue(item, "DT_NASC");
                    if (!String.IsNullOrEmpty(dtnasc))
                        curdate = String.Format("{0:dd/MM/yyyy}", Convert.ToDateTime(dtnasc));
                    nomeDescr = "<div class='row' >";
                    nomeDescr += "<div class='col-xs-12' style='line-height: 120%;'>" + " <i class='fa fa-" + ((Generic.GetItemValue(item, "SEXO") == "F") ? "venus text-pink" : "mars text-blue") + "'></i>&nbsp;" + Generic.GetItemValue(item, "NOME") + " (" + GetBirthDate(Convert.ToDateTime(dtnasc)) + ")";

                    if (!String.IsNullOrEmpty(curdate))
                    {
                        nomeDescr += "<br>";
                        nomeDescr += "<b>Obs: </b>" + " " + Generic.GetItemValue(item, "OBS_CONS") + "</div>";

                    }
                    else
                    {
                        nomeDescr += "</div>";
                    }

                    nomeDescr += " </div>";
                    nomeDescr += "</div>";



                    item.rowItems.First(q => q.itemColumnName == "NOME").itemValue = nomeDescr;

                    #endregion


                    #region Bandage

                    string imagem = "";
                    if (Generic.GetItemValue(item, "COD_SERV").Equals("2154") || Generic.GetItemValue(item, "COD_SERV").Equals("2155") || Generic.GetItemValue(item, "COD_SERV").Equals("1154") || Generic.GetItemValue(item, "COD_SERV").Equals("1112"))
                    {
                        imagem = "<div class='row'>";
                        imagem += "<div class='col-xs-12'>" + " <img src ='/Content/img/bandage.png' height ='36' width ='36'> " + " </div>";
                        imagem += "</div>";
                    }
                    else
                    {
                        imagem = "<div class='row'>";
                        imagem += "<div class='col-xs-12'>" + "<i class='fa fa-minus text-gray' aria-hidden='true'></i>" + " </div>";
                        imagem += "</div>";
                    }
                    item.rowItems.First(q => q.itemColumnName == "IMAGEM").itemValue = imagem;

                    #endregion


                    #region NomeMedico
                    curdate = "";

                    if (Generic.GetItemValue(item, "MEDICO_NOME") != null) {
                        string anota = Generic.GetItemValue(item, "DT_NOTA_MEDICA");
                        int nmedico = Convert.ToInt32(Generic.GetItemValue(item, "MEDICO_ID"));
                        if (nmedico==631 && !String.IsNullOrEmpty(anota))
                        {
                             
                                try
                                {

                                    string oradb = GetConnectionString();
                                    OracleConnection conn = new OracleConnection(ConfigurationManager.ConnectionStrings[HttpContext.Current.Session[Constants.SS_LOCAL_CONN].ToString()].ConnectionString);  // C#
                                    conn.Open();
                                    OracleCommand cmd = new OracleCommand();
                                    cmd.Connection = conn;
                                string medicoID = Generic.GetItemValue(item, "N_CONS");
                                cmd.CommandText = "select DIAMED_MEDICO from DIARIO_MEDICO where N_CONS =" + medicoID;
                                cmd.CommandType = CommandType.Text;
                                    OracleDataReader dr = cmd.ExecuteReader();
                                    dr.Read();
                                    string label1 = dr.GetString(0);
                                    

                                
                                    cmd = new OracleCommand();
                                    cmd.Connection = conn;
                                 
                                    cmd.CommandText = "select NOME from SD_PESS_HOSP_DEF where N_MECAN =" + "'"+label1+"'";
                                    cmd.CommandType = CommandType.Text;
                                    dr = cmd.ExecuteReader();
                                    dr.Read();
                                    string label2 = dr.GetString(0);
                                    conn.Dispose();

                                if (label2!=null)
                                {
                                    item.rowItems.First(q => q.itemColumnName == "MEDICO_NOME").itemValue = label2;


                                }
                                else
                                {
                                    item.rowItems.First(q => q.itemColumnName == "MEDICO_NOME").itemValue = "A Designar Médico";
                                }

                            }
                                    catch (Exception e)
                                    {
                                        item.rowItems.First(q => q.itemColumnName == "MEDICO_NOME").itemValue = "A Designar Médico";
                                    }



                            //item.rowItems.First(q => q.itemColumnName == "MEDICO_NOME").itemValue = Generic.GetItemValue(item, "MEDICO_NOME");
                        }
                        else
                        {
                            item.rowItems.First(q => q.itemColumnName == "MEDICO_NOME").itemValue = Generic.GetItemValue(item, "MEDICO_NOME");
                        }
                        
                    }
                    else
                    {

                        if (Generic.GetItemValue(item, "MEDICO_ID") == null)
                        {
                            item.rowItems.First(q => q.itemColumnName == "MEDICO_NOME").itemValue = "A Designar Médico";

                        }


                    }
                    #endregion


                    #region DataConsulta

                    string admissao, admissao2;
                    string dataAdm = Generic.GetItemValue(item, "DT_CONS");

                    admissao = String.Format("{0:HH:mm}", Convert.ToDateTime(dataAdm));
                    admissao2 = String.Format("{0:dd/MM}", Convert.ToDateTime(dataAdm));
                    DateTime thisDay = DateTime.Today;
                    if (Convert.ToDateTime(dataAdm).DayOfYear + 1 == thisDay.DayOfYear)
                    {
                        admissao2 = "Ontem,";
                    }
                    else if (Convert.ToDateTime(dataAdm).DayOfYear == thisDay.DayOfYear)
                    {
                        admissao2 = "";
                    }

Lusiadas-Solucao-Web/Lusiadas-Solucao-Web/Controllers/ATPController.cs
using LDFHelper.Helpers;
using LusiadasSolucaoWeb.Models;
using Microsoft.Ajax.Utilities;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Oracle.ManagedDataAccess.Client;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Web.Mvc;

namespace LusiadasSolucaoWeb.Controllers
{
    public class ATPController : LDFTableController
    {
        UserInfo uinfo = new UserInfo();

     
        public ActionResult Index()
        {
            if (Session[Constants.SS_USER]!=null)
            {
               
                ATPModel atpTable = new ATPModel();
                return View(atpTable);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            
        }


        public ActionResult Dash(string hosp)
        {

            if (hosp.ToUpper().Equals("PORTO") || hosp.ToUpper().Equals("LISBOA") || hosp.ToUpper().Equals("ALGARVE"))
            {

                switch (hosp.ToUpper())
                {

                    case "PORTO":
                        hosp = "HPT";
                        break;
                    case "LISBOA":
                        hosp = "HLU";
                        break;
                    case "ALGARVE":
                        hosp = "HSUL";
                        break;
                    default:
                        hosp = "";
                        break;
                }

                Session["PERMA"] = "BD" + hosp + "QLD"; ;

            }

            ATPModel atpTable = new ATPModel();
            return View(atpTable);        
            
        }


        [HttpGet]
        public JsonResult LoadTable()
        {
            
            UserInfo uinfo = Session[Constants.SS_USER] as UserInfo;

            List<LDFTableField> listFields = new List<LDFTableField>();


            ATPModel atpModel = new ATPModel();
            _model = atpModel;
            _modelName = "LusiadasSolucaoWeb.Models.ATPModel";

            JsonResult res=LoadLDFTable(1, null, JsonConvert.SerializeObject(listFields));

            return res;

        }

        [HttpGet]
        public string GetDados()
        {
            
            GetData();

            return Globals.nDoentes+";"+Globals.semTriagem+";"+Globals.semNota;

        }


        public JsonResult LoadTableDash(int pagen)
        {


            UserInfo uinfo = Session[Constants.SS_USER] as UserInfo;

            List<LDFTableField> listFields = new List<LDFTableField>();


            ATPModel atpModel = new ATPModel();
            _model = atpModel;
            _modelName = "LusiadasSolucaoWeb.Models.ATPModel";

            JsonResult res = LoadLDFTableDash(pagen, null, JsonConvert.SerializeObject(listFields));

            return res;

        }

        public void GetData()
        {

            try
            {

                string oradb = "";
                if (Session["PERMA"].ToString().Contains("HPT"))
                {

                    oradb = ConfigurationManager.ConnectionStrings["BDHPTQLD"].ConnectionString;
                }
                else if (Session["PERMA"].ToString().Contains("HLU"))
                {
                    oradb = ConfigurationManager.ConnectionStrings["BDHLUQLD"].ConnectionString;
                }
                else
                {
                    oradb = ConfigurationManager.ConnectionStrings["BDHSULQLD"].ConnectionString;
                }
                OracleConnection conn = new Oracle.ManagedDataAccess.Client.OracleConnection(oradb);  // C#
                conn.Open();
                OracleCommand cmd = new OracleCommand();
                cmd.Connection = conn;
                cmd.CommandText = "select count(*) from MEDICO.V_DASH_DESLOC_ATP_V3";
                cmd.CommandType = CommandType.Text;
                OracleDataReader dr = cmd.ExecuteReader();

                if (dr.HasRows)
                {

                    while (dr.Read())
                    {
                        Globals.nDoentes = dr["COUNT(*)"].ToString();

                    }

                }
                else
                {
                    Globals.nDoentes = "Sem Dados";
                }

                OracleCommand cmd2 = new OracleCommand();
                cmd2.Connection = conn;
                cmd2.CommandText = "select count(*) from MEDICO.V_DASH_DESLOC_ATP_V3 where COR_TRIAGEM IS NULL";
                cmd2.CommandType = CommandType.Text;
                OracleDataReader dr2 = cmd2.ExecuteReader();

                if (dr2.HasRows)
                {

                    while (dr2.Read())
                    {
                        Globals.semTriagem = dr2["COUNT(*)"].ToString();

                    }

                }
                else
                {
                    Globals.semTriagem = "Sem Dados";
                }

                OracleCommand cmd3 = new OracleCommand();
                cmd3.Connection = conn;
                cmd3.CommandText = "select count(*) from MEDICO.V_DASH_DESLOC_ATP_V3 where DT_NOTA_MEDICA IS NULL";
                cmd3.CommandType = CommandType.Text;
                OracleDataReader dr3 = cmd3.ExecuteReader();

                if (dr3.HasRows)
                {

                    while (dr3.Read())
                    {
                        Globals.semNota = dr3["COUNT(*)"].ToString();

                    }

                }
                else
                {
                    Globals.semNota = "Sem Dados";
                }





                conn.Dispose();

            }
            catch (Exception err)
            {
               
                string var=err.InnerException.ToString();
                Globals.nDoentes = "Sem Dados";
                Globals.semNota = "Sem Dados";
                Globals.semTriagem = "Sem Dados";

            }


        }


    }
}

Lusiadas-Solucao-Web/Lusiadas-Solucao-Web/Views/ATP/Index.cshtml
@using LDFHelper.Helpers;
@using LusiadasSolucaoWeb.Models;

@model ATPModel


<link href="/Content/css/ldfTable.min.css" rel="stylesheet" />
<script src="/Content/js/ldfTable.min.js"></script>

<script type="text/javascript">

    $(document).ajaxStart(function () {
        $('body').addClass("loading");

    });
    $(document).ajaxStop(function () {
        $('body').removeClass("loading");

    });

    $(document).ajaxError(function (e, jqxhr, settings, exception) {
        $('body').removeClass("loading");

        //e.stopPropagation();
        //if (jqxhr != null) {
        //    alert("De momento n\xE3o \xE9 poss\xEDvel satisfazer o pedido. Pedimos desculpa pelo incomodo");
        //    window.location = "/";
        //}
    });

</script>


<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Atendimento Permanente
        <small>Listagem de doentes</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Início</a></li>
        <li class="active">Atendimento Permanente</li>
    </ol>
</section>


<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-lg-4 col-xs-4">
            <!-- small box -->
            <div class="small-box bg-aqua">
                <div class="inner">
                    <h3 id="numDoentes">Sem Dados</h3>
                    <p>Doentes Presentes</p>
                </div>
                <div class="icon">
                    <i class="fa fa-user"></i>
                </div>
            </div>
        </div><!-- ./col -->
        <div class="col-lg-4 col-xs-4">
            <!-- small box -->
            <div class="small-box bg-yellow">
                <div class="inner">
                    <h3 id="semTriagem">Sem Dados</h3>
                    <p>Sem Triagem</p>
                </div>
                <div class="icon">
                    <i class="fa fa-clock-o"></i>
                </div>
            </div>
        </div><!-- ./col -->
        <div class="col-lg-4 col-xs-4">
            <!-- small box -->
            <div class="small-box bg-orange">
                <div class="inner">
                    <h3 id="semNota">Sem Dados</h3>
                    <p>Sem Nota Médica</p>
                </div>
                <div class="icon">
                    <i class="fa fa-user-md"></i>
                </div>
            </div>
        </div><!-- ./col -->

    </div>

    <div class="row">
        <form action="#" method="post">
            <div class="box box-default">
                <div class="box-body">
                    <div style="max-width:700px;max-height:50px;margin-left:2.5%;">
                        <div style="float:left;">
                            <label>
                                <input type="button" onclick="startRefresh()" id="actualizaATP" />

                            </label>
                        </div>
                        <div style="float:left;margin-left:4%;">
                            @{ DateTime localDate = DateTime.Now; string data = localDate.Hour + ":" + localDate.Minute + ":" + localDate.Second;}
                            <label id="lastupdate">
                                Última Actualização: @data
                            </label>
                            <label>&nbsp;|&nbsp;Legenda:&nbsp;&nbsp; </label><label>RX&nbsp;</label><img src='/Content/img/xray.png' height='24' width='24'><label>&nbsp;ECO&nbsp;</label><img src='/Content/img/ultra.png' height='24' width='24'><label>&nbsp;TAC&nbsp;</label><img src='/Content/img/xcat.png' height='24' width='24'><label>&nbsp;RM&nbsp;</label><img src='/Content/img/rm.png' height='24' width='24'>

                        </div>
                    </div>

                    <div class="row listwrapper no-border">@Html.TableRender(Model, new LDFTableAttributes() { ID = "atpTable", className = "tableInternal" })</div>
                </div>
            </div>
        </form>
    </div>
</section>
<div class="loadingModal"></div>



@section customJS
{
    <script type="text/javascript">



        $(document).ajaxStart(function () {
            $('body').addClass("loading");

        });
        $(document).ajaxStop(function () {
            $('body').removeClass("loading");

        });

        $(document).ajaxError(function (e, jqxhr, settings, exception) {
            $('body').removeClass("loading");

            //e.stopPropagation();
            //if (jqxhr != null) {
            //    alert("De momento n\xE3o \xE9 poss\xEDvel satisfazer o pedido. Pedimos desculpa pelo incomodo");
            //    window.location = "/";
            //}
        });

        //getDados();

        function RefreshData()
        {

             $.ajax({
                url: '@Url.Action("LoadTable", "ATP")',
                type: "get",
                cache: false,
                 success: function (result) {

                     LDFTableRenderBody(result, 'atpTable');
                    


                },
                error: function (xhr, ajaxOptions, thrownError) {
                    console.log(xhr);
                }
            });

        }

        $(function () {
            startRefresh();
        });

        function startRefresh() {



           // setTimeout(startRefresh, 30000);
            var date = new Date;

            var seconds = date.getSeconds();
            var minutes = date.getMinutes();
            var hour = date.getHours();
            $("#lastupdate").empty();

            if (hour < 10) {
                hour = "0" + hour;
            }
            if (minutes < 10) {
                minutes = "0" + minutes;
            }
            if (seconds < 10) {
                seconds = "0" + seconds;
            }

            $("#lastupdate").append("Última Actualização: " + hour + ":" + minutes + ":" + seconds);

            getDados();
         

            //$("#lastupdate") = "Última Actualização: "+hour + ":" + minutes + ":" + seconds;
            


        }


    function getDados() {

        $.ajax({
            url: '@Url.Action("GetDados", "ATP")',
            type: "get",
            cache: false,
            success: function (result) {

                var res=result.split(';');

                var ndoentes =res[0];
                var semTriagem = res[1];
                var semNota =res[2];

                $("#numDoentes").empty();
                $("#numDoentes").append(ndoentes);

                $("#semTriagem").empty();
                $("#semTriagem").append(semTriagem);

                $("#semNota").empty();
                $("#semNota").append(semNota);

                RefreshATPTable();

            },
            timeout: 10000,
            error: function (xhr, ajaxOptions, thrownError) {

                console.log(xhr);
            }
        });

    }



        function RefreshATPTable() {

            LDFTableResetCounter("atpTable");
            RefreshData();

            //$("#sortDesc").removeClass("active");

        }

    </script>
}